// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockDownloader is an autogenerated mock type for the Downloader type
type MockDownloader struct {
	mock.Mock
}

type MockDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloader) EXPECT() *MockDownloader_Expecter {
	return &MockDownloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields:
func (_m *MockDownloader) Download() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDownloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDownloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
func (_e *MockDownloader_Expecter) Download() *MockDownloader_Download_Call {
	return &MockDownloader_Download_Call{Call: _e.mock.On("Download")}
}

func (_c *MockDownloader_Download_Call) Run(run func()) *MockDownloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloader_Download_Call) Return(_a0 error) *MockDownloader_Download_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloader_Download_Call) RunAndReturn(run func() error) *MockDownloader_Download_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDownloader creates a new instance of MockDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloader {
	mock := &MockDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
