# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
---
version: 2

before:
  hooks:
    - go mod tidy
    - go install golang.org/x/tools/cmd/stringer@latest
    - go generate ./...
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - ppc64
    goarm:
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X {{.ModulePath}}/cmd.Version={{.Version}} -X {{.ModulePath}}/cmd.Date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

upx:
  - enabled: true
    compress: best
git:
  ignore_tags:
    - "{{ if not .IsNightly }}nightly{{ end }}"

archives:
  - format: tgz
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch}}{{ end }}
      {{- if .Arm }}_v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - info:
          mtime: "{{ .CommitDate }}"
      - src: CHANGELOG*
        dst: docs
      - src: README*
        dst: docs
      - src: LICENSE*
        dst: docs

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Version }}-snapshot"

changelog:
  disable: true

release:
  github:
    owner: asphaltbuffet
    name: elf
  prerelease: auto

nightly:
  publish_release: true
  keep_single_release: true
  name_template: "{{ incminor .Version }}-nightly"

announce:
  skip: "true"

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/asphaltbuffet/elf
    description: |-
      A helper for programming exercises.
      Elf takes care of the boring parts of programming exercises so you can
      focus on the fun parts.
    maintainer: Ben Lechlitner <otherland@gmail.com>
    license: MIT
    vendor: asphaltbuffet
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/elf.bash
        dst: /usr/share/bash-completion/completions/elf
        file_info:
          mode: 0644
      - src: ./completions/elf.fish
        dst: /usr/share/fish/vendor_completions.d/elf.fish
        file_info:
          mode: 0644
      - src: ./completions/elf.zsh
        dst: /usr/share/zsh/vendor-completions/_elf
        file_info:
          mode: 0644
      - src: ./manpages/
        dst: /usr/share/man/man1/
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/elf/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - golang
    recommends:
      - python3
