dir: mocks/{{.SrcPackageName}}
filename: "mock_{{.InterfaceName}}.go"
log-level: warn
pkgname: mocks
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/asphaltbuffet/elf/cmd/benchmark:
    interfaces:
      Benchmarker: {}
  github.com/asphaltbuffet/elf/cmd/download:
    interfaces:
      Downloader: {}
  github.com/asphaltbuffet/elf/cmd/solve:
    interfaces:
      Challenge: {}
  github.com/asphaltbuffet/elf/cmd/test:
    interfaces:
      ChallengeTester: {}
  github.com/asphaltbuffet/elf/cmd/analyze:
    interfaces:
      Analyzer: {}
  github.com/asphaltbuffet/elf/pkg/krampus:
    interfaces:
      ConfigurationReader: {}
      DownloadConfiguration: {}
      ExerciseConfiguration: {}
  github.com/asphaltbuffet/elf/pkg/runners:
    interfaces:
      Runner: {}
