with-expecter: true
outpkg: mocks
dir: "mocks/{{.PackageName}}"
log-level: "info"
packages:
    github.com/asphaltbuffet/elf/pkg/runners:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            Runner:
    github.com/asphaltbuffet/elf/pkg/krampus:
        config:
        interfaces:
            DownloadConfiguration:
            ExerciseConfiguration:
            ConfigurationReader:
    github.com/asphaltbuffet/elf/cmd:
        config:
        interfaces:
            Benchmarker:
            Downloader:
            Challenge:
            ChallengeTester:
            Grapher:
    github.com/asphaltbuffet/elf/pkg/analysis:
        config:
        interfaces:
            Analyzer: