with-expecter: true
outpkg: mocks
packages:
    github.com/asphaltbuffet/elf/pkg/runners:
        # place your package-specific config here
        config:
        interfaces:
            # select the interfaces you want mocked
            Runner:
                # Modify package-level config for this specific interface (if applicable)
                config:
                  log-level: "info"
                  dir: "mocks/{{.InterfaceName}}"