schema = 3

[mod]
  [mod."charm.land/lipgloss/v2"]
    version = "v2.0.0-beta.3.0.20251106193318-19329a3e8410"
    hash = "sha256-iLsJGqxaSpBKMpM+K8oA7OKUydjBAdDl80Y3Xnf1xVA="
  [mod."codeberg.org/go-fonts/liberation"]
    version = "v0.5.0"
    hash = "sha256-wh966QuMEiha0jG3D9WB+qEAMbSAlFJd2eAzB1scf6U="
  [mod."codeberg.org/go-latex/latex"]
    version = "v0.2.0"
    hash = "sha256-xt30xhMCdegFiVoXyQiRucvBiWbILSKL1dHcy23aOyQ="
  [mod."codeberg.org/go-pdf/fpdf"]
    version = "v0.11.1"
    hash = "sha256-rA9FaMdc6CG+F0dkDz4DT/cMtXVc88Q8bvK4T0zShHs="
  [mod."git.sr.ht/~sbinet/gg"]
    version = "v0.7.0"
    hash = "sha256-3iLPzAmcjbuvjdOWaYvpynQJR6lq3ymqnWzvJceYHlk="
  [mod."github.com/ajstarks/svgo"]
    version = "v0.0.0-20211024235047-1546f124cd8b"
    hash = "sha256-sPwt5sImKFk949TzUeYEF2UiJDqHxXFJKRL2Y7JWJ6Y="
  [mod."github.com/aymanbagabas/go-osc52/v2"]
    version = "v2.0.1"
    hash = "sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg="
  [mod."github.com/charmbracelet/colorprofile"]
    version = "v0.4.2"
    hash = "sha256-AMnmwWjpv/TMb2mbqVXB4RmMVWBsrTFlq1FL8A00olw="
  [mod."github.com/charmbracelet/fang"]
    version = "v0.4.4"
    hash = "sha256-KnwAd/LVJC5gxO/xT80NduudQqA8JNnoDRFE77k30qs="
  [mod."github.com/charmbracelet/lipgloss"]
    version = "v1.1.0"
    hash = "sha256-RHsRT2EZ1nDOElxAK+6/DC9XAaGVjDTgPvRh3pyCfY4="
  [mod."github.com/charmbracelet/ultraviolet"]
    version = "v0.0.0-20260213120247-99b01dfd139c"
    hash = "sha256-htTLRXxRDgWFq7EGQWqQHK795yiHn9E4uu0czvvfRB8="
  [mod."github.com/charmbracelet/x/ansi"]
    version = "v0.11.6"
    hash = "sha256-UToZIkqXl9MEppcRgbeBqaaMeAzRkGa0w3lVUs6sxWI="
  [mod."github.com/charmbracelet/x/cellbuf"]
    version = "v0.0.15"
    hash = "sha256-0S60XaWhKZG+TB3Kqe1oMn2Okwdq53nym8XayVSHHiM="
  [mod."github.com/charmbracelet/x/exp/charmtone"]
    version = "v0.0.0-20260209194814-eeb2896ac759"
    hash = "sha256-Q6ouXSvCucqKj3S7J0r7lyxQ1NpiuF80mgkmgnvtvMw="
  [mod."github.com/charmbracelet/x/term"]
    version = "v0.2.2"
    hash = "sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4="
  [mod."github.com/charmbracelet/x/termios"]
    version = "v0.1.1"
    hash = "sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds="
  [mod."github.com/charmbracelet/x/windows"]
    version = "v0.2.2"
    hash = "sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk="
  [mod."github.com/clipperhouse/displaywidth"]
    version = "v0.10.0"
    hash = "sha256-RIPgA9Z5HFywV1XIsMFmvt1ypMh/JkGvvP8GJu3jsC4="
  [mod."github.com/clipperhouse/uax29/v2"]
    version = "v2.6.0"
    hash = "sha256-5ZkKO0DXNfsF179i0iDjH+Ir7W78bGdQRgJdDIRoHnc="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.2-0.20180830191138-d8f796af33cc"
    hash = "sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.9.0"
    hash = "sha256-WtpE1N6dpHwEvIub7Xp/CrWm0fd6PX7MKA4PV44rp2g="
  [mod."github.com/go-resty/resty/v2"]
    version = "v2.17.1"
    hash = "sha256-cI7Kexg8Q2kiQKBNyUFW8vO2E65i3Ov8IeUwoQ2NuWU="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.5.0"
    hash = "sha256-LbrCBANBprVI84M0CWrXc7rriJL5ac5VKbh58LBTw7U="
  [mod."github.com/golang/freetype"]
    version = "v0.0.0-20170609003504-e2365dfdc4a0"
    hash = "sha256-AHAFBd20/tqxohkWyQkui2bUef9i1HWYgk9LOIFErvA="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jarcoal/httpmock"]
    version = "v1.3.1"
    hash = "sha256-LmP4JWkjWFnJq/F+O1eaeLuKH93pQgFRkDJQm0obh3c="
  [mod."github.com/lmittmann/tint"]
    version = "v1.1.3"
    hash = "sha256-+jkEUI3fxhE4zBJ+b8LBV7e0+1n1wJo4Za6Mn45XdoE="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.3.0"
    hash = "sha256-6BKrJsfmxie+YFAWzTYVPQfrwjQEXRo+J8LY+50C1BU="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.19"
    hash = "sha256-GpnbKplhX410Q/eIdknvWbYZgdav1keN+7wNUeOSMHE="
  [mod."github.com/mitchellh/colorstring"]
    version = "v0.0.0-20190213212951-d06e56a500db"
    hash = "sha256-dg5havre+NkxU85tbWXgdhjVtVnkNfTVa999HX+JVbQ="
  [mod."github.com/montanaflynn/stats"]
    version = "v0.7.1"
    hash = "sha256-0QXUA/syOtDSBooh3isAffrVAjpSoBmSMMuZfO5maHg="
  [mod."github.com/muesli/cancelreader"]
    version = "v0.2.2"
    hash = "sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ="
  [mod."github.com/muesli/mango"]
    version = "v0.2.0"
    hash = "sha256-hEu9ZE2yYBCD2O9KNq8Lgc8dGeCPrTgx/b0tZtTToJk="
  [mod."github.com/muesli/mango-cobra"]
    version = "v1.3.0"
    hash = "sha256-VPE2A9eyMI63789PcnM5Ltm5PWt/yewWVh7hKtyoe4c="
  [mod."github.com/muesli/mango-pflag"]
    version = "v0.2.0"
    hash = "sha256-gF9oIQpH9iGFEzDOrfgurtVOd1BjGmSRMkNDnSJClcw="
  [mod."github.com/muesli/roff"]
    version = "v0.1.0"
    hash = "sha256-0A/M8h0+dSF1NruiGjs4WbfWENFbV3VpyIwJzHEeRlA="
  [mod."github.com/muesli/termenv"]
    version = "v0.16.0"
    hash = "sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI="
  [mod."github.com/pelletier/go-toml/v2"]
    version = "v2.2.4"
    hash = "sha256-8qQIPldbsS5RO8v/FW/se3ZsAyvLzexiivzJCbGRg2Q="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.1-0.20181226105442-5d4384ee4fb2"
    hash = "sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90="
  [mod."github.com/rivo/uniseg"]
    version = "v0.4.7"
    hash = "sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.14.1"
    hash = "sha256-6NzhXCCD1Qhj05WHbCDxH5hwfNM6psoAk7uIxm7N55E="
  [mod."github.com/sagikazarmark/locafero"]
    version = "v0.12.0"
    hash = "sha256-EXk9S5Z5sYyApAzCgHIugsGMbt/pHWRfHYFZH5D+5Ws="
  [mod."github.com/schollz/progressbar/v3"]
    version = "v3.19.0"
    hash = "sha256-ABW5J1C0XgtVYV+7N6g6/ZGMKOzF4iingBS7ruvO5S8="
  [mod."github.com/spf13/afero"]
    version = "v1.15.0"
    hash = "sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8="
  [mod."github.com/spf13/cast"]
    version = "v1.10.0"
    hash = "sha256-dQ6Qqf26IZsa6XsGKP7GDuCj+WmSsBmkBwGTDfue/rk="
  [mod."github.com/spf13/cobra"]
    version = "v1.10.2"
    hash = "sha256-nbRCTFiDCC2jKK7AHi79n7urYCMP5yDZnWtNVJrDi+k="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.10"
    hash = "sha256-uDPnWjHpSrzXr17KEYEA1yAbizfcsfo5AyztY2tS6ZU="
  [mod."github.com/spf13/viper"]
    version = "v1.21.0"
    hash = "sha256-A9A8i7HH/ge4j3hw7G++HNj8BjhhpZKvxHhfY+QAxkI="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.3"
    hash = "sha256-4s8d7MdRKq4r7QjkIFCdwjKehc6Hi5mS4xuZ2v2QYR8="
  [mod."github.com/stretchr/testify"]
    version = "v1.11.1"
    hash = "sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc="
  [mod."github.com/subosito/gotenv"]
    version = "v1.6.0"
    hash = "sha256-LspbjTniiq2xAICSXmgqP7carwlNaLqnCTQfw2pa80A="
  [mod."github.com/xo/terminfo"]
    version = "v0.0.0-20220910002029-abceb7e1c41e"
    hash = "sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU="
  [mod."go.yaml.in/yaml/v3"]
    version = "v3.0.4"
    hash = "sha256-NkGFiDPoCxbr3LFsI6OCygjjkY0rdmg5ggvVVwpyDQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240909161429-701f63a606c0"
    hash = "sha256-nB3zQGSyCNU9Z6QP0iYYBpUeu7HKBBXS1z9ba4DxjMQ="
  [mod."golang.org/x/image"]
    version = "v0.36.0"
    hash = "sha256-cPp26T1QPhpLwDz0SHsLlrVi8Q7ytxdiBrOtxNXcYl8="
  [mod."golang.org/x/net"]
    version = "v0.50.0"
    hash = "sha256-A3tvRuVotO4d8S1FX9ri9CpMJacrFJmHebLJ5m9b+Ss="
  [mod."golang.org/x/sync"]
    version = "v0.19.0"
    hash = "sha256-RbRZ+sKZUurOczGhhzOoY/sojTlta3H9XjL4PXX/cno="
  [mod."golang.org/x/sys"]
    version = "v0.41.0"
    hash = "sha256-owjs3/IzAKfFlIz1U1fiHSfl2+bTUhaXTyWEjL5SWHk="
  [mod."golang.org/x/term"]
    version = "v0.40.0"
    hash = "sha256-tu8USqDmcWfwery/+xti/BdUpNLbMNmZeghBNDsj1fQ="
  [mod."golang.org/x/text"]
    version = "v0.34.0"
    hash = "sha256-wGKd1JkeiFROibvo2kkAuQ7JajSIfV4utGaoGbTQhQM="
  [mod."gonum.org/v1/plot"]
    version = "v0.16.0"
    hash = "sha256-OKE4/1H54grm+BDQE0qGYMsmFpyGcO5PFuryzOPPv7c="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20201130134442-10cb98267c6c"
    hash = "sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
