version: "3"

tasks:
    check:
        desc: test and lint
        cmds:
            - task: test
            - task: lint

    dev:
        desc: dev build pipeline
        cmds:
            - task: generate
            - task: mock
            - task: lint
            - task: test
            - task: snapshot

    ci:
        desc: ci build pipeline
        deps: [generate, mock]
        cmds:
            - task: mod-tidy
            - task: install
            - task: test
            - task: build
            - task: diff

    clean:
        desc: remove files created during build pipeline
        cmds:
            - rm -rf dist
            - rm -rf bin
            - rm -rf mocks

    nuke:
        desc: go clean + remove build artifacts
        deps: [clean]
        cmds:
            - go clean -i -cache -testcache -modcache -fuzzcache -x

    mod-tidy:
        desc: go mod tidy
        aliases: [mod]
        cmds:
            - go mod tidy
        sources:
            - "**/*.go"
        generates:
            - go.mod
            - go.sum

    install:
        desc: install tools
        cmds:
            - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
            - go install mvdan.cc/gofumpt@v0.4.0
            - go install gotest.tools/gotestsum@latest
            - go install github.com/goreleaser/goreleaser@latest

    generate:
        desc: generate artifacts
        deps: [install-stringer]
        aliases: [gen]
        cmds:
            - go generate ./...

    install-stringer:
        internal: true
        cmds:
            - go install golang.org/x/tools/cmd/stringer@latest
        status:
            - if ! command -v mockery &> /dev/null; then exit 1; fi

    mock:
        desc: generate mocks
        deps: [install-mockery]
        cmds:
            - mockery --log-level=warn

    install-mockery:
        internal: true
        cmds:
            - go install github.com/vektra/mockery/v2@v2.40.1
        status:
            - if ! command -v mockery &> /dev/null; then exit 1; fi

    build:
        desc: go build
        cmds:
            - go build -o dist/ ./...

    snapshot:
        desc: goreleaser build snapshot
        deps: [install, mod-tidy, generate]
        aliases: [ss]
        cmds:
            - goreleaser build --clean --single-target --snapshot

    lint:
        desc: golangci-lint
        deps: [mod-tidy, generate, mock]
        cmds:
            - cmd: mkdir -p bin
              silent: true
            - golangci-lint run --fix --out-format=html:bin/golangci-lint.html,colored-line-number:stdout
        sources:
            - "**/*.go"
        generates:
            - bin/golangci-lint.html

    test:
        desc: go test
        deps: [generate, install, mock]
        cmds:
            - cmd: mkdir -p bin
              silent: true
            - gotestsum -- -race -covermode=atomic -coverprofile=bin/coverage.out $(go list ./... | grep -v /mocks)
            - go tool cover -html=bin/coverage.out -o bin/coverage.html
            - go tool cover -func=bin/coverage.out
        sources:
            - "**/*.go"
            - "**/testdata/**"
        generates:
            - bin/coverage.out
            - bin/coverage.html

    diff:
        desc: git diff
        cmds:
            - git diff --exit-code
            - RES="$(git status --porcelain)" ; if [ -n "$RES" ]; then echo $RES && exit 1 ; fi
