version: '3'

tasks:
  check:
    desc: test and lint
    cmds: 
      - task: test
      - task: lint

  dev:
    desc: dev build pipeline
    cmds:
      - task: generate
      - task: lint
      - task: test
      - task: snapshot

  ci:
    desc: ci build pipeline
    deps: [mod-tidy, install]
    cmds: 
      - task: generate
      - task: test
      - task: build 
      - task: diff

  clean:
    desc: remove files created during build pipeline
    cmds:
      - rm -rf dist
      - rm -rf bin

  nuke:
    desc: go clean + remove build artifacts
    deps: [clean]
    cmds:
      - go clean -i -cache -testcache -modcache -fuzzcache -x

  mod-tidy:
    desc: go mod tidy
    aliases: [mod]
    cmds:
      - go mod tidy
    sources:
      - go.mod
      - go.sum

  install:
    desc: install tools
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - go install mvdan.cc/gofumpt@v0.4.0
      - go install gotest.tools/gotestsum@v1.11.0
    status:
      - test -f $(go env GOPATH)/bin/golangci-lint
      - test -f $(go env GOPATH)/bin/gofumpt
      - test -f $(go env GOPATH)/bin/gotestsum

  generate: 
    desc: go generate
    cmds:
      - go generate ./...

  build: 
    desc: go build
    cmds:
      - go build -o dist/ ./...

  snapshot: 
    desc: goreleaser build snapshot
    aliases: [ss]
    cmds:
      - goreleaser build --clean --single-target --snapshot

  lint: 
    desc: golangci-lint
    cmds: 
      - golangci-lint run --fix

  test:
    desc: go test
    cmds:
      - mkdir -p bin
      - gotestsum --format=dots-v2 -- -race -covermode=atomic -coverprofile=bin/coverage.out ./...
      - go tool cover -html=bin/coverage.out -o bin/coverage.html
      - go tool cover -func=bin/coverage.out
    generates:
      - bin/coverage.out
      - bin/coverage.html

  diff:
    desc: git diff
    cmds:
      - git diff --exit-code
      - RES=$$(git status --porcelain) ; if [ -n "$$RES" ]; then echo $$RES && exit 1 ; fi
