version: "3"

vars:
  GORELEASER_VERSION: "2.0.1-pro"

tasks:
  build:
    desc: go build
    cmds:
      - go build -o dist/ ./...

  ci:
    desc: ci build pipeline
    cmds:
      - task: setup
      - task: generate
      - task: mock
      - task: mod-tidy
      - task: test
      - task: cover
      - task: build
      - task: diff

  clean:
    desc: remove files created during build pipeline
    run: once
    cmds:
      - for: [dist, bin, completions, manpages, release_notes]
        cmd: rm -rf {{.ITEM}}
      - go clean -i -cache -testcache -modcache -fuzzcache -x

  cover:
    desc: go test coverage
    deps: [test]
    cmds:
      - go tool cover -html=bin/coverage.out -o bin/coverage.html
      - go tool cover -func=bin/coverage.out
    sources:
      - bin/coverage.out
    generates:
      - bin/coverage.html

  dev:
    desc: dev build pipeline
    cmds:
      - task: generate
      - task: mock
      - task: lint
      - task: test
      - task: snapshot

  diff:
    desc: git diff
    cmds:
      - git diff --exit-code
      - RES="$(git status --porcelain)" ; if [ -n "$RES" ]; then echo $RES && exit 1 ; fi

  generate:
    desc: generate artifacts
    aliases: [gen]
    run: once
    cmds:
      - 'go generate ./...'

  install-goreleaser:
    cmds:
      - 'curl -sSfLO https://github.com/goreleaser/goreleaser-pro/releases/download/v{{.GORELEASER_VERSION}}/goreleaser-pro_{{.GORELEASER_VERSION}}_amd64.deb'
      - sudo dpkg -i goreleaser-pro*.deb
      - rm goreleaser-pro*.deb
    status:
      - test -z $GITHUB_TOKEN
      - 'goreleaser --version | grep -q {{.GORELEASER_VERSION}}'

  lint:
    desc: golangci-lint
    deps: [generate, mock]
    cmds:
      - cmd: mkdir -p bin
        silent: true
      - 'go tool golangci-lint run --fix --out-format=html:bin/golangci-lint.html,colored-line-number:stdout'
    sources:
      - "**/*.go"
      - ".golangci.yml"
    generates:
      - bin/golangci-lint.html

  mock:
    desc: generate mocks
    run: once
    cmds:
      - 'go tool mockery --log-level=warn'

  mod-tidy:
    desc: go mod tidy
    aliases: [mod]
    run: once
    cmds:
      - go mod tidy
    sources:
      - "**/*.go"
      - "**/go.mod"
      - "**/go.sum"
    generates:
      - "**/go.mod"
      - "**/go.sum"

  snapshot:
    desc: goreleaser build snapshot
    deps: [mod-tidy]
    aliases: [ss]
    cmds:
      - task: generate
      - goreleaser build --clean --single-target --snapshot
    preconditions:
      - sh: goreleaser check -q
        msg: "failed to validate .goreleaser.yml"

  test:
    desc: go test
    deps: [generate, mock]
    run: once
    cmds:
      - cmd: mkdir -p bin
        silent: true
      - 'go tool gotestsum -- -race -covermode=atomic -coverprofile=bin/coverage.out $(go list ./... | grep -v /mocks)'
    sources:
      - "**/*.go"
      - "**/testdata/**"
    generates:
      - bin/coverage.out
