// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/asphaltbuffet/elf/pkg/tasks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChallenge creates a new instance of MockChallenge. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChallenge(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChallenge {
	mock := &MockChallenge{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChallenge is an autogenerated mock type for the Challenge type
type MockChallenge struct {
	mock.Mock
}

type MockChallenge_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChallenge) EXPECT() *MockChallenge_Expecter {
	return &MockChallenge_Expecter{mock: &_m.Mock}
}

// Solve provides a mock function for the type MockChallenge
func (_mock *MockChallenge) Solve(b bool) ([]tasks.Result, error) {
	ret := _mock.Called(b)

	if len(ret) == 0 {
		panic("no return value specified for Solve")
	}

	var r0 []tasks.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) ([]tasks.Result, error)); ok {
		return returnFunc(b)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) []tasks.Result); ok {
		r0 = returnFunc(b)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(b)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChallenge_Solve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Solve'
type MockChallenge_Solve_Call struct {
	*mock.Call
}

// Solve is a helper method to define mock.On call
//   - b bool
func (_e *MockChallenge_Expecter) Solve(b interface{}) *MockChallenge_Solve_Call {
	return &MockChallenge_Solve_Call{Call: _e.mock.On("Solve", b)}
}

func (_c *MockChallenge_Solve_Call) Run(run func(b bool)) *MockChallenge_Solve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChallenge_Solve_Call) Return(results []tasks.Result, err error) *MockChallenge_Solve_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockChallenge_Solve_Call) RunAndReturn(run func(b bool) ([]tasks.Result, error)) *MockChallenge_Solve_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockChallenge
func (_mock *MockChallenge) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChallenge_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockChallenge_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockChallenge_Expecter) String() *MockChallenge_String_Call {
	return &MockChallenge_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockChallenge_String_Call) Run(run func()) *MockChallenge_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChallenge_String_Call) Return(s string) *MockChallenge_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChallenge_String_Call) RunAndReturn(run func() string) *MockChallenge_String_Call {
	_c.Call.Return(run)
	return _c
}
