#!/usr/bin/env bash

#MISE description="remove build artifacts"

declare -a dirs=("dist" "bin" "completions" "manpages" "release_notes")

for d in "${dirs[@]}"; do
  rm -rf $d
done

go clean -i -cache -testcache -modcache -fuzzcache -x
