#!/usr/bin/env bash
#MISE description="lint project files"
#MISE depends=["generate", "mock"]
#MISE sources=["**/*.go", ".golangci.yml"]
#MISE outputs=["bin/golangci-lint.html"]

mkdir -p bin

golangci-lint run \
  --fix \
  --output.html.path=bin/golangci-lint.html \
  --output.text.path=stdout
