#!/usr/bin/env bash
#MISE description="generate manpages"
#MISE hide=true
#MISE sources=["**/*.go"]
#MISE outputs=["manpages/*.gz"]

set -euo pipefail

rm -rf manpages
mkdir manpages

go run . man
gzip -9 manpages/*.1
