// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	afero "github.com/spf13/afero"

	mock "github.com/stretchr/testify/mock"

	slog "log/slog"
)

// MockDownloadConfiguration is an autogenerated mock type for the DownloadConfiguration type
type MockDownloadConfiguration struct {
	mock.Mock
}

type MockDownloadConfiguration_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloadConfiguration) EXPECT() *MockDownloadConfiguration_Expecter {
	return &MockDownloadConfiguration_Expecter{mock: &_m.Mock}
}

// GetBaseDir provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetBaseDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBaseDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetBaseDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBaseDir'
type MockDownloadConfiguration_GetBaseDir_Call struct {
	*mock.Call
}

// GetBaseDir is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetBaseDir() *MockDownloadConfiguration_GetBaseDir_Call {
	return &MockDownloadConfiguration_GetBaseDir_Call{Call: _e.mock.On("GetBaseDir")}
}

func (_c *MockDownloadConfiguration_GetBaseDir_Call) Run(run func()) *MockDownloadConfiguration_GetBaseDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetBaseDir_Call) Return(_a0 string) *MockDownloadConfiguration_GetBaseDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetBaseDir_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetBaseDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheDir provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetCacheDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCacheDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetCacheDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheDir'
type MockDownloadConfiguration_GetCacheDir_Call struct {
	*mock.Call
}

// GetCacheDir is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetCacheDir() *MockDownloadConfiguration_GetCacheDir_Call {
	return &MockDownloadConfiguration_GetCacheDir_Call{Call: _e.mock.On("GetCacheDir")}
}

func (_c *MockDownloadConfiguration_GetCacheDir_Call) Run(run func()) *MockDownloadConfiguration_GetCacheDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetCacheDir_Call) Return(_a0 string) *MockDownloadConfiguration_GetCacheDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetCacheDir_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetCacheDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfigDir provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetConfigDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetConfigDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigDir'
type MockDownloadConfiguration_GetConfigDir_Call struct {
	*mock.Call
}

// GetConfigDir is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetConfigDir() *MockDownloadConfiguration_GetConfigDir_Call {
	return &MockDownloadConfiguration_GetConfigDir_Call{Call: _e.mock.On("GetConfigDir")}
}

func (_c *MockDownloadConfiguration_GetConfigDir_Call) Run(run func()) *MockDownloadConfiguration_GetConfigDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetConfigDir_Call) Return(_a0 string) *MockDownloadConfiguration_GetConfigDir_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetConfigDir_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetConfigDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetFs provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetFs() afero.Fs {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFs")
	}

	var r0 afero.Fs
	if rf, ok := ret.Get(0).(func() afero.Fs); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(afero.Fs)
		}
	}

	return r0
}

// MockDownloadConfiguration_GetFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFs'
type MockDownloadConfiguration_GetFs_Call struct {
	*mock.Call
}

// GetFs is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetFs() *MockDownloadConfiguration_GetFs_Call {
	return &MockDownloadConfiguration_GetFs_Call{Call: _e.mock.On("GetFs")}
}

func (_c *MockDownloadConfiguration_GetFs_Call) Run(run func()) *MockDownloadConfiguration_GetFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetFs_Call) Return(_a0 afero.Fs) *MockDownloadConfiguration_GetFs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetFs_Call) RunAndReturn(run func() afero.Fs) *MockDownloadConfiguration_GetFs_Call {
	_c.Call.Return(run)
	return _c
}

// GetInputFilename provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetInputFilename() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetInputFilename")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetInputFilename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInputFilename'
type MockDownloadConfiguration_GetInputFilename_Call struct {
	*mock.Call
}

// GetInputFilename is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetInputFilename() *MockDownloadConfiguration_GetInputFilename_Call {
	return &MockDownloadConfiguration_GetInputFilename_Call{Call: _e.mock.On("GetInputFilename")}
}

func (_c *MockDownloadConfiguration_GetInputFilename_Call) Run(run func()) *MockDownloadConfiguration_GetInputFilename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetInputFilename_Call) Return(_a0 string) *MockDownloadConfiguration_GetInputFilename_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetInputFilename_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetInputFilename_Call {
	_c.Call.Return(run)
	return _c
}

// GetLanguage provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetLanguage() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLanguage")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetLanguage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLanguage'
type MockDownloadConfiguration_GetLanguage_Call struct {
	*mock.Call
}

// GetLanguage is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetLanguage() *MockDownloadConfiguration_GetLanguage_Call {
	return &MockDownloadConfiguration_GetLanguage_Call{Call: _e.mock.On("GetLanguage")}
}

func (_c *MockDownloadConfiguration_GetLanguage_Call) Run(run func()) *MockDownloadConfiguration_GetLanguage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetLanguage_Call) Return(_a0 string) *MockDownloadConfiguration_GetLanguage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetLanguage_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetLanguage_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogger provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetLogger() *slog.Logger {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogger")
	}

	var r0 *slog.Logger
	if rf, ok := ret.Get(0).(func() *slog.Logger); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slog.Logger)
		}
	}

	return r0
}

// MockDownloadConfiguration_GetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogger'
type MockDownloadConfiguration_GetLogger_Call struct {
	*mock.Call
}

// GetLogger is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetLogger() *MockDownloadConfiguration_GetLogger_Call {
	return &MockDownloadConfiguration_GetLogger_Call{Call: _e.mock.On("GetLogger")}
}

func (_c *MockDownloadConfiguration_GetLogger_Call) Run(run func()) *MockDownloadConfiguration_GetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetLogger_Call) Return(_a0 *slog.Logger) *MockDownloadConfiguration_GetLogger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetLogger_Call) RunAndReturn(run func() *slog.Logger) *MockDownloadConfiguration_GetLogger_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with given fields:
func (_m *MockDownloadConfiguration) GetToken() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockDownloadConfiguration_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockDownloadConfiguration_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockDownloadConfiguration_Expecter) GetToken() *MockDownloadConfiguration_GetToken_Call {
	return &MockDownloadConfiguration_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockDownloadConfiguration_GetToken_Call) Run(run func()) *MockDownloadConfiguration_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloadConfiguration_GetToken_Call) Return(_a0 string) *MockDownloadConfiguration_GetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDownloadConfiguration_GetToken_Call) RunAndReturn(run func() string) *MockDownloadConfiguration_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDownloadConfiguration creates a new instance of MockDownloadConfiguration. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloadConfiguration(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloadConfiguration {
	mock := &MockDownloadConfiguration{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
