// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/asphaltbuffet/elf/pkg/exercise"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDownloader creates a new instance of MockDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloader {
	mock := &MockDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDownloader is an autogenerated mock type for the Downloader type
type MockDownloader struct {
	mock.Mock
}

type MockDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloader) EXPECT() *MockDownloader_Expecter {
	return &MockDownloader_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type MockDownloader
func (_mock *MockDownloader) Download() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDownloader_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDownloader_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
func (_e *MockDownloader_Expecter) Download() *MockDownloader_Download_Call {
	return &MockDownloader_Download_Call{Call: _e.mock.On("Download")}
}

func (_c *MockDownloader_Download_Call) Run(run func()) *MockDownloader_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloader_Download_Call) Return(err error) *MockDownloader_Download_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDownloader_Download_Call) RunAndReturn(run func() error) *MockDownloader_Download_Call {
	_c.Call.Return(run)
	return _c
}

// FilePath provides a mock function for the type MockDownloader
func (_mock *MockDownloader) FilePath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FilePath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDownloader_FilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FilePath'
type MockDownloader_FilePath_Call struct {
	*mock.Call
}

// FilePath is a helper method to define mock.On call
func (_e *MockDownloader_Expecter) FilePath() *MockDownloader_FilePath_Call {
	return &MockDownloader_FilePath_Call{Call: _e.mock.On("FilePath")}
}

func (_c *MockDownloader_FilePath_Call) Run(run func()) *MockDownloader_FilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloader_FilePath_Call) Return(s string) *MockDownloader_FilePath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDownloader_FilePath_Call) RunAndReturn(run func() string) *MockDownloader_FilePath_Call {
	_c.Call.Return(run)
	return _c
}

// Report provides a mock function for the type MockDownloader
func (_mock *MockDownloader) Report() exercise.Report {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Report")
	}

	var r0 exercise.Report
	if returnFunc, ok := ret.Get(0).(func() exercise.Report); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exercise.Report)
		}
	}
	return r0
}

// MockDownloader_Report_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Report'
type MockDownloader_Report_Call struct {
	*mock.Call
}

// Report is a helper method to define mock.On call
func (_e *MockDownloader_Expecter) Report() *MockDownloader_Report_Call {
	return &MockDownloader_Report_Call{Call: _e.mock.On("Report")}
}

func (_c *MockDownloader_Report_Call) Run(run func()) *MockDownloader_Report_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDownloader_Report_Call) Return(report exercise.Report) *MockDownloader_Report_Call {
	_c.Call.Return(report)
	return _c
}

func (_c *MockDownloader_Report_Call) RunAndReturn(run func() exercise.Report) *MockDownloader_Report_Call {
	_c.Call.Return(run)
	return _c
}
