// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"
	"log/slog"

	"github.com/asphaltbuffet/elf/pkg/runners"
	"github.com/asphaltbuffet/elf/pkg/tasks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChallengeTester creates a new instance of MockChallengeTester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChallengeTester(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChallengeTester {
	mock := &MockChallengeTester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChallengeTester is an autogenerated mock type for the ChallengeTester type
type MockChallengeTester struct {
	mock.Mock
}

type MockChallengeTester_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChallengeTester) EXPECT() *MockChallengeTester_Expecter {
	return &MockChallengeTester_Expecter{mock: &_m.Mock}
}

// String provides a mock function for the type MockChallengeTester
func (_mock *MockChallengeTester) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockChallengeTester_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockChallengeTester_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockChallengeTester_Expecter) String() *MockChallengeTester_String_Call {
	return &MockChallengeTester_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockChallengeTester_String_Call) Run(run func()) *MockChallengeTester_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockChallengeTester_String_Call) Return(s string) *MockChallengeTester_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockChallengeTester_String_Call) RunAndReturn(run func() string) *MockChallengeTester_String_Call {
	_c.Call.Return(run)
	return _c
}

// Test provides a mock function for the type MockChallengeTester
func (_mock *MockChallengeTester) Test(ctx context.Context, logger *slog.Logger, runner runners.Runner, w io.Writer, cb func(tasks.Result)) ([]tasks.Result, error) {
	ret := _mock.Called(ctx, logger, runner, w, cb)

	if len(ret) == 0 {
		panic("no return value specified for Test")
	}

	var r0 []tasks.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, runners.Runner, io.Writer, func(tasks.Result)) ([]tasks.Result, error)); ok {
		return returnFunc(ctx, logger, runner, w, cb)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, runners.Runner, io.Writer, func(tasks.Result)) []tasks.Result); ok {
		r0 = returnFunc(ctx, logger, runner, w, cb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tasks.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, runners.Runner, io.Writer, func(tasks.Result)) error); ok {
		r1 = returnFunc(ctx, logger, runner, w, cb)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChallengeTester_Test_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Test'
type MockChallengeTester_Test_Call struct {
	*mock.Call
}

// Test is a helper method to define mock.On call
//   - ctx context.Context
//   - logger *slog.Logger
//   - runner runners.Runner
//   - w io.Writer
//   - cb func(tasks.Result)
func (_e *MockChallengeTester_Expecter) Test(ctx interface{}, logger interface{}, runner interface{}, w interface{}, cb interface{}) *MockChallengeTester_Test_Call {
	return &MockChallengeTester_Test_Call{Call: _e.mock.On("Test", ctx, logger, runner, w, cb)}
}

func (_c *MockChallengeTester_Test_Call) Run(run func(ctx context.Context, logger *slog.Logger, runner runners.Runner, w io.Writer, cb func(tasks.Result))) *MockChallengeTester_Test_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 runners.Runner
		if args[2] != nil {
			arg2 = args[2].(runners.Runner)
		}
		var arg3 io.Writer
		if args[3] != nil {
			arg3 = args[3].(io.Writer)
		}
		var arg4 func(tasks.Result)
		if args[4] != nil {
			arg4 = args[4].(func(tasks.Result))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockChallengeTester_Test_Call) Return(results []tasks.Result, err error) *MockChallengeTester_Test_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockChallengeTester_Test_Call) RunAndReturn(run func(ctx context.Context, logger *slog.Logger, runner runners.Runner, w io.Writer, cb func(tasks.Result)) ([]tasks.Result, error)) *MockChallengeTester_Test_Call {
	_c.Call.Return(run)
	return _c
}
