// Code generated by "stringer -type=TaskStatus"; DO NOT EDIT.

package advent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invalid-0]
	_ = x[Passed-1]
	_ = x[Unverified-2]
	_ = x[Failed-3]
	_ = x[Error-4]
}

const _TaskStatus_name = "InvalidPassedUnverifiedFailedError"

var _TaskStatus_index = [...]uint8{0, 7, 13, 23, 29, 34}

func (i TaskStatus) String() string {
	if i < 0 || i >= TaskStatus(len(_TaskStatus_index)-1) {
		return "TaskStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskStatus_name[_TaskStatus_index[i]:_TaskStatus_index[i+1]]
}
