// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/asphaltbuffet/elf/pkg/protocol"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function for the type MockRunner
func (_mock *MockRunner) Cleanup() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockRunner_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
func (_e *MockRunner_Expecter) Cleanup() *MockRunner_Cleanup_Call {
	return &MockRunner_Cleanup_Call{Call: _e.mock.On("Cleanup")}
}

func (_c *MockRunner_Cleanup_Call) Run(run func()) *MockRunner_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_Cleanup_Call) Return(err error) *MockRunner_Cleanup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Cleanup_Call) RunAndReturn(run func() error) *MockRunner_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockRunner
func (_mock *MockRunner) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRunner_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRunner_Expecter) Close(ctx interface{}) *MockRunner_Close_Call {
	return &MockRunner_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockRunner_Close_Call) Run(run func(ctx context.Context)) *MockRunner_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRunner_Close_Call) Return(err error) *MockRunner_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockRunner_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Open provides a mock function for the type MockRunner
func (_mock *MockRunner) Open(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Open")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Open_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Open'
type MockRunner_Open_Call struct {
	*mock.Call
}

// Open is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRunner_Expecter) Open(ctx interface{}) *MockRunner_Open_Call {
	return &MockRunner_Open_Call{Call: _e.mock.On("Open", ctx)}
}

func (_c *MockRunner_Open_Call) Run(run func(ctx context.Context)) *MockRunner_Open_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRunner_Open_Call) Return(err error) *MockRunner_Open_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Open_Call) RunAndReturn(run func(ctx context.Context) error) *MockRunner_Open_Call {
	_c.Call.Return(run)
	return _c
}

// Prepare provides a mock function for the type MockRunner
func (_mock *MockRunner) Prepare(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Prepare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Prepare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prepare'
type MockRunner_Prepare_Call struct {
	*mock.Call
}

// Prepare is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRunner_Expecter) Prepare(ctx interface{}) *MockRunner_Prepare_Call {
	return &MockRunner_Prepare_Call{Call: _e.mock.On("Prepare", ctx)}
}

func (_c *MockRunner_Prepare_Call) Run(run func(ctx context.Context)) *MockRunner_Prepare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRunner_Prepare_Call) Return(err error) *MockRunner_Prepare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Prepare_Call) RunAndReturn(run func(ctx context.Context) error) *MockRunner_Prepare_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, task *protocol.Task) (*protocol.Result, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *protocol.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *protocol.Task) (*protocol.Result, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *protocol.Task) *protocol.Result); ok {
		r0 = returnFunc(ctx, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protocol.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *protocol.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - task *protocol.Task
func (_e *MockRunner_Expecter) Run(ctx interface{}, task interface{}) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run", ctx, task)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, task *protocol.Task)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *protocol.Task
		if args[1] != nil {
			arg1 = args[1].(*protocol.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(result *protocol.Result, err error) *MockRunner_Run_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, task *protocol.Task) (*protocol.Result, error)) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// String provides a mock function for the type MockRunner
func (_mock *MockRunner) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRunner_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockRunner_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockRunner_Expecter) String() *MockRunner_String_Call {
	return &MockRunner_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockRunner_String_Call) Run(run func()) *MockRunner_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRunner_String_Call) Return(s string) *MockRunner_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRunner_String_Call) RunAndReturn(run func() string) *MockRunner_String_Call {
	_c.Call.Return(run)
	return _c
}
