name: Lint
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up mise
        uses: jdx/mise-action@v3

      - name: Autogenerate files
        run: mise run generate

      - name: Create output directory
        run: mkdir -p bin

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.8
